apiVersion: v1 # K8S API Version
kind: Pod  # Object Type
metadata: 
 name: nginx-animals
spec:
 containers: 
 - name: spring-music
   image: yanivomc/spring-music:latest 
   ports: 
   - containerPort: 8080
 - name: animals
   image: supergiantkir/animals:bear
   ports: 
   - containerPort: 80
