apiVersion: v1 # K8S API Version
kind: Pod  # Object Type
metadata: 
 name: nginx-animals
spec:
 containers: 
 - name: spring-music
   volumeMounts:
   - name: spring-music-persistent-storage
     mountPath: /storage
   image: yanivomc/spring-music:latest 
   ports: 
   - containerPort: 8080
 - name: animals
   volumeMounts:
  - name: animals-persistent-storage
    mountPath: /storage
   image: supergiantkir/animals:bear
   ports: 
   - containerPort: 80
  
volumes:
 - name: app-storage
   hostPath:
    # directory location on host
    path: /tmp/files
    # this field is optional
    type: Directory
