apiVersion: apps/v1 # K8S API Version
kind: ReplicaSet  # Object Type
metadata: 
 name: frontend
 labels:
  app: spring
  tier: fe
spec:
 replicas: 2
 selector:
  matchLabels:
   tier: frontend
 template: 
  metadata:
   labels:
    tier: frontend
  spec:
   containers: 
   - name: spring-music
     volumeMounts:
     - name: app-storage
       mountPath: /spring-music-storage
     image: yanivomc/spring-music:latest 
     ports: 
     - containerPort: 8080
   - name: animals
     volumeMounts:
     - name: app-storage
       mountPath: /animals-storage
     image: supergiantkir/animals:bear
     ports: 
     - containerPort: 80
   volumes:
   - name: app-storage
     hostPath:
      path: /tmp/files
